# Site settings
title: GarthDB
email: garthdb@gmail.com
description: "Ramblings of Garth Braithwaite."
baseurl: ""
url: "http://garthdb.github.io/"
sass:
  sass_dir: css
  style: compressed

# Build settings
markdown: kramdown
permalink: /:categories/:title/

highlighter: pygments
