# Site settings
title: GarthDB
email: garthdb@gmai.com
description: "Ramblings of Garth Braithwaite."
baseurl: ""
url: "http://garthdb.github.io/"
sass:
    sass_dir: css

# Build settings
markdown: kramdown
permalink: /:categories/:title/
