# Site settings
title: GarthDB
email: garthdb@gmail.com
logo: /img/logo.svg
author:
  name: Garth Braithwaite
  uri: http://garthdb.com
  twitter: garthdb
description: "Ramblings of Garth Braithwaite."
twitter:
  username: garthdb
gems:
  - jekyll-seo-tag
  - jekyll-feed
baseurl: ""
url: "http://garthdb.com"
sass:
  sass_dir: css
  style: compressed

# Build settings
markdown: kramdown
permalink: /:categories/:title/

defaults:
  -
    scope:
      path: ""
    values:
      image:
        twitter: /img/twitter_card.png
