# Site settings
title: GarthDB
email: garthdb@gmail.com
logo: /img/logo.svg
author:
  name: Garth Braithwaite
  uri: http://garthdb.com
  twitter: garthdb
description: "Ramblings of Garth Braithwaite."
image:
  twitter: "http://garthdb.com/img/twitter_card.png"
twitter:
  username: garthdb
gems:
  - jekyll-seo-tag
  - jekyll-feed
baseurl: ""
url: "http://garthdb.com"
sass:
  sass_dir: css
  style: compressed

# Build settings
markdown: kramdown
permalink: /:categories/:title/
